spring:
  server:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ads-analysis
    username: root
    password: 123456
    hikari:


    multipart:
      max-file-size: 30MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB
      enabled: true
  sql:
    init:
      mode: always
server:
  port: 8081
